# Safety Security and License Configuration file
# To validate and review your policy file, run the validate command: `safety validate policy_file --path <path-to-this-file>`
security: # configuration for the `safety check` command
  ignore-cvss-severity-below: 0 # A severity number between 0 and 10. Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity. 7=ignore all vulnerabilities except CRITICAL & HIGH severity. 4=ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity.
  ignore-cvss-unknown-severity: False
  ignore-vulnerabilities: # Here you can list multiple specific vulnerabilities you want to ignore (optionally for a time period)
    54843:
      reason: We don't make use of the effected functionality
      expires: "2023-07-31" # datetime string - date this ignore will expire, best practice to use this variable
    45185:
      reason: We have to use dslinter for the project, and it's not compatible with pylint>=2.13.0
      expires: "2023-07-31"
    54370:
      reason: We have to use dslinter for the project, and it's not compatible with pyspark>=3.1.0
      expires: "2023-07-31"
    54576:
      reason: We have to use dslinter for the project, and it's not compatible with pyspark>=3.1.0
      expires: "2023-07-31"
    54694:
      reason: We have to use dslinter for the project, and it's not compatible with pyspark>=3.1.0
      expires: "2023-07-31"

  continue-on-vulnerability-error: False # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities.
